#!/usr/bin/env bash
#Using your debugging skills, find out what’s keeping your Ubuntu container’s 
#Nginx installation from listening on port 80
# A Bash script with the minimum number of commands to automate your fix.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
