#!/bin/bash

case "$1" in
  start)
    if [ -f /var/run/my_process.pid ]; then
      echo "manage_my_process is already running."
      exit 1
    fi
    ./manage_my_process &
    echo $! > /var/run/my_process.pid
    echo "manage_my_process started"
    ;;
  stop)
    if [ ! -f /var/run/my_process.pid ]; then
      echo "manage_my_process is not running."
      exit 1
    fi
    kill $(cat /var/run/my_process.pid)
    rm /var/run/my_process.pid
    echo "manage_my_process stopped"
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    echo "manage_my_process restarted"
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac
